### ISSUE TITLE
Questionable terminology

### ISSUE THREAD

**Issue by bortzmeyer** [Zensavona/domainatrex#20]
Example from the documentation:

```
iex> Domainatrex.parse("blog.someone.id.au")
{:ok, %{domain: "someone", subdomain: "blog", tld: "id.au"}}
```

The field called `tld`  should have a better name. In the above example, it is not even a TLD.  Call it ` suffix` or ` registration_domain` .

(The field `domain` is also not ideal. May be ` registered_domain`?)

**Comment by Zensavona** [comment]
Appreciate the input and I agree `suffix` may be a better term, but I think users understand what I mean here and breaking compatibility is not worth the change.
